### ISSUE TITLE
Can't modify version_num in Google Cloud Spanner

### ISSUE THREAD

**Issue by Romeo-PHILLIPS** [googleapis/python-spanner-sqlalchemy#174]
Thanks for stopping by to ask us a question! Please make sure to include:
- What you're trying to do
Hello, I'm trying to use Alembic with SQLAlchemy-spanner to do database migration. I've setup everything, the data is moving except that alembic to keep track on the current version stores the current version inside version_num in a table that it creates in Spanner. The issue with that is that Spanner needs a primary key, and so version_num is the primary key. So when upgrading/downgrading Alembic tries to UPDATE to the latest version but fails.

- What code you've already tried
I've tried setting version_table_pk to True/False inside the alembic.ini but no luck.

- Any error messages you're getting
`sqlalchemy.exc.OperationalError: (google.cloud.spanner_dbapi.exceptions.RetryAborted) The transaction was aborted and could not be retried due to a concurrent modification.
[SQL: UPDATE alembic_version SET version_num='fcc8665532bb' WHERE alembic_version.version_num = 'e13c982601c9']
`

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

**Comment by Romeo-PHILLIPS** [comment]
I seem to have fixed this issue by creating the table and adding another field (primary key) along with the version_num field. Now my other issue is that when I run an upgrade via transaction (for example removing a column), it tries (from what I understand) to do two transactions and then commit both, which is why I believe it fails (the first transaction seems to work while the second fails, which is the updating of the version).

`(venv) MacBook-Pro-de-Romeo:echo-data-lake strum$ alembic downgrade -1
INFO  [alembic.runtime.migration] Context impl SpannerImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
INFO  [sqlalchemy.engine.base.Engine] BEGIN (implicit)
INFO  [sqlalchemy.engine.base.Engine] SELECT alembic_version.version_num 
FROM alembic_version
INFO  [sqlalchemy.engine.base.Engine] []
INFO  [alembic.runtime.migration] Running downgrade c40d612878ba -> 20d37e1ad678, revision test2
INFO  [sqlalchemy.engine.base.Engine] ALTER TABLE test_migration_table DROP COLUMN test1
INFO  [sqlalchemy.engine.base.Engine] []
INFO  [sqlalchemy.engine.base.Engine] UPDATE alembic_version SET version_num='20d37e1ad678' WHERE alembic_version.version_num = 'c40d612878ba'
INFO  [sqlalchemy.engine.base.Engine] []
INFO  [sqlalchemy.engine.base.Engine] ROLLBACK
Traceback (most recent call last):
  File "/Users/strum/PycharmProjects/echo-data-lake/venv/lib/python3.9/site-packages/google/api_core/grpc_helpers.py", line 156, in error_remapped_callable
    return _StreamingResponseIterator(
  File "/Users/strum/PycharmProjects/echo-data-lake/venv/lib/python3.9/site-packages/google/api_core/grpc_helpers.py", line 82, in __init__
    self._stored_first_result = next(self._wrapped)
  File "/Users/strum/PycharmProjects/echo-data-lake/venv/lib/python3.9/site-packages/grpc/_channel.py", line 426, in __next__
    return self._next()
  File "/Users/strum/PycharmProjects/echo-data-lake/venv/lib/python3.9/site-packages/grpc/_channel.py", line 826, in _next
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
        status = StatusCode.ABORTED
        details = "Transaction aborted. Database schema probably changed during transaction, retry may succeed."
        debug_error_string = "{"created":"@1639587199.482586000","description":"Error received from peer ipv4:172.217.168.170:443","file":"src/core/lib/surface/call.cc","file_line":1064,"grpc_message":"Transaction aborted. Database schema probably changed during transaction, retry may succeed.","grpc_status":10}"
>
`

**Comment by IlyaFaer** [comment]
@Romeo-PHILLIPS, it looks like in both cases the error is caused by concurrent transactions. Unlikely primary keys have something to do with it.

Alembic, AFAIK, doesn't provide and sync/lock mechanisms by default, so it's up to user to control the flows.
Can you post your migration script?

**Comment by Romeo-PHILLIPS** [comment]
> @Romeo-PHILLIPS, it looks like in both cases the error is caused by concurrent transactions. Unlikely primary keys have something to do with it.
> 
> Alembic, AFAIK, doesn't provide and sync/lock mechanisms by default, so it's up to user to control the flows. Can you post your migration script?

Hello, thank you for your answer! Here is my basic migration script:

`def upgrade():
    op.add_column('test_migration_table', sa.Column('test1234567', String(100)))


def downgrade():
    op.drop_column('test_migration_table', 'test1')
`

And here is my env.py


`
class SpannerImpl(DefaultImpl):
    __dialect__ = "spanner"
    # transactional_ddl = True


def run_migrations_offline():
    """Run migrations in 'offline' mode.

    This configures the context with just a URL
    and not an Engine, though an Engine is acceptable
    here as well.  By skipping the Engine creation
    we don't even need a DBAPI to be available.

    Calls to context.execute() here emit the given string to the
    script output.

    """
    url = config.get_main_option("sqlalchemy.url")
    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
    )

    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online():
    """Run migrations in 'online' mode.

    In this scenario we need to create an Engine
    and associate a connection with the context.

    """
    connectable = engine_from_config(
        config.get_section(config.config_ini_section),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )

    with connectable.connect() as connection:
        context.configure(
            connection=connection, target_metadata=target_metadata, transactional_ddl=True
        )

        with context.begin_transaction() as transaction:
            context.run_migrations()
            # transaction.commit()



if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()

`

**Comment by IlyaFaer** [comment]
@Romeo-PHILLIPS, the very first thing that caught my eyes is this option:
`transactional_ddl=True`

See the section: https://github.com/googleapis/python-spanner-sqlalchemy#ddl-and-transactions
So, at least, the option will have no effect. But I suspect it can even bring some problems, so I'd start with erasing it from the script.

**Comment by Romeo-PHILLIPS** [comment]
> @Romeo-PHILLIPS, the very first thing that caught my eyes is this option: `transactional_ddl=True`
> 
> See the section: https://github.com/googleapis/python-spanner-sqlalchemy#ddl-and-transactions So, at least, the option will have no effect. But I suspect it can even bring some problems, so I'd start with erasing it from the script.

So I removed that attribute, and here are the logs when downgrading:

```
(venv) MacBook-Pro-de-Romeo:echo-data-lake strum$ alembic downgrade -1
INFO  [alembic.runtime.migration] Context impl SpannerImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
INFO  [sqlalchemy.engine.base.Engine] BEGIN (implicit)
INFO  [sqlalchemy.engine.base.Engine] SELECT alembic_version.version_num 
FROM alembic_version
INFO  [sqlalchemy.engine.base.Engine] []
INFO  [alembic.runtime.migration] Running downgrade c40d612878ba -> 20d37e1ad678, revision test2
INFO  [sqlalchemy.engine.base.Engine] ALTER TABLE test_migration_table DROP COLUMN test1
INFO  [sqlalchemy.engine.base.Engine] []
INFO  [sqlalchemy.engine.base.Engine] UPDATE alembic_version SET version_num='20d37e1ad678' WHERE alembic_version.version_num = 'c40d612878ba'
INFO  [sqlalchemy.engine.base.Engine] []
INFO  [sqlalchemy.engine.base.Engine] ROLLBACK

```

The table is dropped, but Alembic doesn't manage to update the current version of the table:

```
  File "/Users/strum/PycharmProjects/echo-data-lake/venv/lib/python3.9/site-packages/google/cloud/spanner_dbapi/connection.py", line 263, in retry_transaction
    self._rerun_previous_statements()
  File "/Users/strum/PycharmProjects/echo-data-lake/venv/lib/python3.9/site-packages/google/cloud/spanner_dbapi/connection.py", line 298, in _rerun_previous_statements
    _compare_checksums(statement.checksum, retried_checksum)
  File "/Users/strum/PycharmProjects/echo-data-lake/venv/lib/python3.9/site-packages/google/cloud/spanner_dbapi/checksum.py", line 78, in _compare_checksums
    raise RetryAborted(
sqlalchemy.exc.OperationalError: (google.cloud.spanner_dbapi.exceptions.RetryAborted) The transaction was aborted and could not be retried due to a concurrent modification.
[SQL: UPDATE alembic_version SET version_num='20d37e1ad678' WHERE alembic_version.version_num = 'c40d612878ba']
(Background on this error at: http://sqlalche.me/e/13/e3q8)

```

**Comment by IlyaFaer** [comment]
```python
ValueError: `staleness` option can't be changed while a transaction is in progress. Commit or rollback the current transaction and try again.
```
Quite strange. It looks like a connection is returned back to connections pool, but it's not commited or rolledback. I'll think about it.

We have an auto-retry mechanism for aborted transactions. Meaning it can retry to execute a statement for 50 times in case of a failure. If you'll try to run another migration while it's still retrying, you'll most likely get concurrent transactions.

I'm not yet manage to repeat your error, but while I'm attempting, you can try to check what's happening with transactions when you're running migrations (see [the docs](https://cloud.google.com/spanner/docs/introspection/transaction-statistics)).

**Comment by Romeo-PHILLIPS** [comment]
Here is a log in terms of latency when I get:

```
sqlalchemy.exc.OperationalError: (google.cloud.spanner_dbapi.exceptions.RetryAborted) The transaction was aborted and could not be retried due to a concurrent modification.
[SQL: UPDATE alembic_version SET version_num='0b2b1fd9ac72' WHERE alembic_version.version_num = '1dfb931fb327']
```

<img width="1286" alt="Capture d’écran 2021-12-20 à 10 30 30" src="https://user-images.githubusercontent.com/92714362/146753278-1787e5ff-c1c3-4662-b553-195562733662.png">

**Comment by IlyaFaer** [comment]
@Romeo-PHILLIPS, still didn't manage to reproduce your case...

So, you're running a migration, first update - it adds a column and changes the revision in the table. Here everything works fine.
When you do downgrade, it actually downgrades the table, but fails on a revision change... What's the revision value after the fail?

Looking at the traceback you provided, I see that the transaction was aborted, then it was retried, but retried steps are not the same, which were made on the original transaction. And in your logs I see it's still trying to do transactional DDLs, here:
```
(venv) MacBook-Pro-de-Romeo:echo-data-lake strum$ alembic downgrade -1
INFO  [alembic.runtime.migration] Context impl SpannerImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
INFO  [sqlalchemy.engine.base.Engine] BEGIN (implicit)
```
It should not, attempt to do transactional DDLs will bring troubles. We're using completely different mechanism for DDLs, which never works in the same transaction as the following statements.
