### ISSUE TITLE
`version.py` missing from source on PyPI

### ISSUE THREAD

**Issue by xylar** [googleapis/python-spanner-sqlalchemy#337]
I'm trying to build `sqlalchemy-spanner` on conda-forge from the source from PyPI. In our CI, I'm seeing:
```
Traceback (most recent call last):
    File "<string>", line 2, in <module>
    File "<pip-setuptools-caller>", line 34, in <module>
    File "/home/conda/feedstock_root/build_artifacts/sqlalchemy-spanner_1692018227156/work/setup.py", line 39, in <module>
      with open(VERSION_FILENAME) as f:
           ^^^^^^^^^^^^^^^^^^^^^^
  FileNotFoundError: [Errno 2] No such file or directory: '/home/conda/feedstock_root/build_artifacts/sqlalchemy-spanner_1692018227156/work/version.py'
  error: subprocess-exited-with-error
```
I'm seeing this for 1.2.0 but I checked the source for 1.6.2 on PyPI and `version.py` appears still to be missing.

A solution for us is to build from source from GitHub but this is less convenient.  It would be nice to have `version.py` included with the source on PyPI as well.

**Comment by xylar** [comment]
Just reporting that more than a year on, this is still a problem.

**Comment by chawatphonr** [comment]
Encountered this issue as well.

**Comment by mkumarpcln** [comment]
yep @ssabdb that's what we're doing as well. I've added `sqlalchemy-spanner==1.11.0` before `apache-airflow-providers-google` on the `requirements.txt`

**Comment by xboy2k11** [comment]
Yeah, this is going to bite a lot of people moving toward Airflow 3.x - the recommended pin fix does work for us as well.
